spring:
  application:
    name: Poker Chase Application
  datasource:
    url: jdbc:postgresql://localhost:5432/poker
    username: poker
    password: poker
    jpa:
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    liquibase:
      enabled: true
      change-log: classpath:db/changelog/db.changelog-master.yaml
security:
  jwt:
    secret: secret
    expiration: 86400000

blockchain:
  rpc:
    url: "http://127.0.0.1:8545"
  contract:
    address: "0x73382711A28e26B5CEBC99Be13321657Cf53cef5"
  wallet:
    privateKey: "0xdc53880b634d0dbf7c28d510c9019869f116409e510fabb43eeabff7df8ad163"